In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
no.arange(0,10,2)

NameError: name 'no' is not defined

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5,5)

TypeError: data type not understood

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

linspace includes 0 and 10!!!!!

In [17]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random,rand(2)

NameError: name 'rand' is not defined

In [20]:
np.random.rand(2)

array([0.83275582, 0.54016152])

In [21]:
np.random.rand(5,5)

array([[0.91714171, 0.09804398, 0.90697948, 0.90349054, 0.00901023],
       [0.0770696 , 0.92400278, 0.66655999, 0.53708078, 0.63988051],
       [0.51209023, 0.54555214, 0.39318517, 0.53200845, 0.51965817],
       [0.18365184, 0.47496647, 0.10074053, 0.83817171, 0.34179975],
       [0.39947565, 0.1923605 , 0.2151189 , 0.31626808, 0.63638283]])

In [22]:
np.random.randn(5,5)

array([[ 0.33586028,  0.34934602, -0.75071954,  0.57627148, -0.91934897],
       [ 0.62778885, -1.31367821, -0.27603962,  0.05130786,  0.59544874],
       [-0.07571625,  0.35213072,  1.37737906, -1.03289442,  0.29973971],
       [-0.44080744, -0.52671975,  1.41890432, -0.44942767, -0.63185751],
       [ 0.42636   ,  0.99293362, -1.32607682, -0.52240238,  0.29813885]])

In [23]:
np.random.randint(1,100)

45

In [24]:
np.random.randint(1,100,20)

array([33, 73, 74, 35, 85, 52, 75,  1, 54, 37, 84, 21, 10, 78, 23, 25, 58,
       81, 94, 91])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

NameError: name 'ranarr' is not defined

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([47, 36,  6, 38,  9, 39,  5, 46,  8, 41])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:

ranarr

array([47, 36,  6, 38,  9, 39,  5, 46,  8, 41])

In [32]:
ranarr.max()

47

In [33]:
ranarr.min()

5

In [34]:
ranarr.argmax()

0

In [35]:
ranarr.argmin()

6

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
arr.reshape(1,25).shape

(1, 25)

In [39]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [40]:
arr.reshape(25,1).shape

(25, 1)

In [41]:
arr.dtype

dtype('int64')

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[8]

8

In [45]:
arr[0]

0

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr(:5)

SyntaxError: invalid syntax (<ipython-input-47-db258eda079e>, line 1)

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[:5] = 100

In [51]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr = arr[:6]

In [55]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [56]:
slice_of_arr[:3] = 199

In [57]:
arr

array([199, 199, 199,   3,   4,   5,   6,   7,   8,   9,  10])

In [58]:
arr_copy = arr.copy()

In [59]:
arr_copy

array([199, 199, 199,   3,   4,   5,   6,   7,   8,   9,  10])

In [60]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [61]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr_2d[2][1]

8

In [63]:
arr_2d[2,1]

8

In [64]:
arr_2d[0:1,1:2]

array([[2]])

In [65]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [66]:
arr_2d[1]

array([4, 5, 6])

In [67]:
arr_2d[1,:]

array([4, 5, 6])

In [68]:
arr_2d[:,1]

array([2, 5, 8])

In [69]:
arr2d = np.zeros((10,10))

In [70]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
arr

array([199, 199, 199,   3,   4,   5,   6,   7,   8,   9,  10])

In [72]:
arr_length = arr2d.shape[1]

In [73]:
arr_length

10